
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>
    <title>WCF exception received on closing connection with callbacks in use - RunCode</title>
    <meta name="keywords" content="c#,.net,wcf,deadlock"/>
    <meta name="description" content="fighting off my fair share of WCF exceptions as anybody who has worked with WCF would know..) but this error is one that is proving to be quite resilient.  To paint "/>
    <link rel="stylesheet" href="/answer/styles/css.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="/answer/styles/prettify/prettify.css" type="text/css"/>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="/answer/styles/js.js"></script>
    <script type="text/javascript" src="/answer/styles/prettify/prettify.js"></script>
</head>
<body>
<div id="doc">
    
<div id="header">
    <div>
        <a title="RunCode" href="http://www.runcode.us" class="logo">
            <img src="/answer/styles/images/logo.png" alt="RunCode"/>
        </a>
        <span class="navigator"><a href="http://www.runcode.us" title="RunCode">Visit Home</a></span>
    </div>
</div>
    <h1><a href="http://wc.runcode.us/q/wcf-exception-received-on-closing-connection-with-callbacks-in-use" title="WCF exception received on closing connection with callbacks in use">WCF exception received on closing connection with callbacks in use</a></h1>

    <div id="sidebar">
        <h3>Relate Answers</h3>
        <ul>
            
                <li>
                    <div class="r_t"><a href="http://an.runcode.us/q/android-broadcast-receiver-and-force-close-uncaught-exceptions" title="Android Broadcast Receiver and Force Close (Uncaught exceptions)">Android Broadcast Receiver and Force Close (Uncaught exceptions)</a></div>

                    <div class="r_c">Hi, 

I have a multi Activity application with a quit/logout button on most of the screens. 

On pressing the button it shows a confirmation dialog and then sends out a &#039;quit&#039; broadcast. 

I have a broadcast receiver on each of ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://us.runcode.us/q/using-callbacks-except-in-certain-cases" title="Using callbacks except in certain cases">Using callbacks except in certain cases</a></div>

                    <div class="r_c">I have a Rails callback for a quantitative model that updates some numbers based on recent activity, something like:

class Data &amp;lt; ActiveRecord::Base
before_validation :check_numbers

def check_numbers
  Check #1...
  Check #2...
  Check #3...
  Check #4...
  ...etc.
end


All of these checks add up to quite ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receive" title="The underlying connection was closed: An unexpected error occurred on a receive.">The underlying connection was closed: An unexpected error occurred on a receive.</a></div>

                    <div class="r_c">When I try my program on my win2k8 machine it runs fine but on win 2k3 it gives me this error that error message

here&#039;s the code that&#039; generating the error

 WebClient wc = new WebClient();
 wc.DownloadFile(&#034;ftp://ftp.website.com/sample.txt&#034;);


have search the web for ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receive-3" title="The underlying connection was closed: An unexpected error occurred on a receive">The underlying connection was closed: An unexpected error occurred on a receive</a></div>

                    <div class="r_c">First, sorry for my en english, i&#039;m french and it&#039;s well known that french people are pretty bad in foreign languages.

I&#039;m here because i have a problem while downloading some files through ftp protocol. It&#039;s weird because it occurs ocasionnally ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receive-4" title="The underlying connection was closed: An unexpected error occurred on a receive">The underlying connection was closed: An unexpected error occurred on a receive</a></div>

                    <div class="r_c">Using a console app which runs as a scheduled task on Azure, to all a long(ish) running webpage on Azure.  

Problem after a few minutes: The underlying connection was closed: An unexpected error occurred on a receive 

 //// used ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receive-1" title="The underlying connection was closed: An unexpected error occurred on a receive.">The underlying connection was closed: An unexpected error occurred on a receive.</a></div>

                    <div class="r_c">When I try my program on my win2k8 machine it runs fine but on win 2k3 it gives me this error that error message

here&#039;s the code that&#039; generating the error

WebClient wc = new WebClient(); 
wc.DownloadFile(&#034;ftp://ftp.website.com/sample.zip&#034;);


there&#039;s the weird part. if i ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-receive-2" title="The underlying connection was closed: An unexpected error occurred on a receive">The underlying connection was closed: An unexpected error occurred on a receive</a></div>

                    <div class="r_c">Hi,

We are using Reporting Service(SSRS 2008) webservice(ReportingService2005.asmx, ReportingExecutionService2005.asmx) to export/Render the report into PDF format from Windows application. When exporting the huge amount of data contain report(Upto 10MB), then we are getting exception as &#034;The underlying connection was closed: An ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://re.runcode.us/q/receiving-datagrams-using-udp-connection" title="Receiving datagrams using Udp connection">Receiving datagrams using Udp connection</a></div>

                    <div class="r_c">In order to receive datagrams through an UDP connection I have created an object of type UDPClient.

 receivedNotificationSock = new UdpClient();


However once done and on using the receive method:

 receivedHostNameBuffer=receivedNotificationSock.Receive(ref receivedNotificationIP);


I am getting an exception saying that I must call ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://ja.runcode.us/q/java-oracle-connection-pooling-closed-connection-exception" title="Java Oracle connection pooling - Closed Connection exception">Java Oracle connection pooling - Closed Connection exception</a></div>

                    <div class="r_c">Hello,

This post is intended to be less of a question and more a confirmation that I&#039;m doing things correctly. I&#039;ve seen many similar posts but I&#039;m not sure I fully understand everything that&#039;s been said.

The problem is that, after a ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://if.runcode.us/q/if-i-catch-exceptions-inside-a-using-statement-for-a-sqlconnection-does-the-using-still-handle-closing-and-disposing-my-connection" title="If I catch exceptions inside a using statement for a SqlConnection, does the using still handle closing and disposing my connection?">If I catch exceptions inside a using statement for a SqlConnection, does the using still handle closing and disposing my connection?</a></div>

                    <div class="r_c">I&#039;m going through some old C#.NET code in an ASP.NET application making sure that all SqlConnections are wrapped in using blocks.

This piece of code used to open cn and da and close and dispose them in both the catch block ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://cl.runcode.us/q/closing-connections-within-a-using-block" title="closing connections within a using block">closing connections within a using block</a></div>

                    <div class="r_c">On reading lots of code, I find that a given Connection object, which implements IDisposable, is is manually closed within a using statement. I see this when I see code related to MySQL.

It&#039;s not needed to be explicitly closed. Why ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://wh.runcode.us/q/when-calling-an-ienumerable-over-a-wcf-service-i-receive-the-underlying-connection-was-closed-error" title="When calling an IEnumerable over a WCF Service I receive The underlying connection was closed error">When calling an IEnumerable over a WCF Service I receive The underlying connection was closed error</a></div>

                    <div class="r_c">Bit of background on my question...

I have a website and multiple console apps that access the same data layer (Linq-To-Sql) to set/get data.  The console apps run across our network and they all update the central database via WCF services. ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://th.runcode.us/q/thread-used-for-serviceconnection-callback-android" title="Thread used for ServiceConnection callback (Android)">Thread used for ServiceConnection callback (Android)</a></div>

                    <div class="r_c">Hi

I&#039;m developing an activity that binds to a local service (in onCreate of the activity):  

bindService(new Intent(this, CommandService.class), svcConn, BIND_AUTO_CREATE);  


I would like to be able to call methods through the IBinder in my lifecycle methods, but can not be ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://ex.runcode.us/q/exception-when-trying-codefirst-with-wcf-entityconnection-can-only-be-constructed-with-a-closed-dbconnection" title="Exception when trying codefirst with WCF &#034;EntityConnection can only be constructed with a closed DbConnection&#034;">Exception when trying codefirst with WCF &#034;EntityConnection can only be constructed with a closed DbConnection&#034;</a></div>

                    <div class="r_c">I am keep getting the following exception when trying to access database in my WCF application using codefirst technique:

&#034;EntityConnection can only be constructed with a closed DbConnection&#034;

I have installed EntityFrameowrk using the NuGet package.

And implemented CodeFirst as per the following ...</div>
                </li>
            
                <li>
                    <div class="r_t"><a href="http://wc.runcode.us/q/wcf-decorating-ienumerable-t-with-datamember-causes-exception-the-underlying-connection-was-closed-the-connection-was-closed-unexpectedly" title="WCF - Decorating IEnumerable&lt;T&gt; with DataMember causes Exception:The underlying connection was closed: The connection was closed unexpectedly">WCF - Decorating IEnumerable&lt;T&gt; with DataMember causes Exception:The underlying connection was closed: The connection was closed unexpectedly</a></div>

                    <div class="r_c">I have created a WCF service which returns IEnumerable&lt;CyberResourceProvisioningAction&gt;.

The CyberResourceProvisioningAction type has a property of AccountInformation IEnumerable&lt;CyberResourceProvisioningActionAccountInfo&gt;. When I decorate the AccountInformation property with DataMemberAttribute I receive the exception:


  WCF System.Net.WebException: The
  underlying connection was closed: The
  connection was closed ...</div>
                </li>
            
        </ul>
    </div>
    <div id="main">
        <div class="question">
            <div class="as1">
                <div class="aa1">
					<script type="text/javascript"><!--
					google_ad_client = "ca-pub-7610814771568026";
					/* code */
					google_ad_slot = "0144905949";
					google_ad_width = 336;
					google_ad_height = 280;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
                </div>
                <div class="aa1">
					<script type="text/javascript"><!--
					google_ad_client = "ca-pub-7610814771568026";
					/* code */
					google_ad_slot = "0144905949";
					google_ad_width = 336;
					google_ad_height = 280;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
                </div>
            </div>
            <div class="q_c">
                <div class="author">
                    <img src="http://www.gravatar.com/avatar/23fff93ede98c6cd922ef17b68b38a0c?d=identicon"/><br/>
                    <a href="http://stackoverflow.com/users/41211" class="a_link" target="_blank">GONeale</a>
                </div>
                <div class="q_t">
                    <p>Hey there all,</p>

<p>I am using a <code>netNamedPipeBinding</code> to perform inter-process WCF communication from a windows app to a windows service.</p>

<p>Now my app is running well in all other accounts (after fighting off my fair share of WCF exceptions as anybody who has worked with WCF would know..) but this error is one that is proving to be quite resilient.</p>

<p>To paint a picture of my scenario: my windows service could be queued to do some work at any given time through a button pressed in the windows app and it then talks over the <code>netNamedPipeBinding</code> which is a binding that supports callbacks (two-way communication) if you are not familiar and initiates a request to perform this work, (in this case a file upload procedure) it also throws the callbacks (events) every few seconds ranging from file progress to transfer speed etc. etc. back to the windows app, so there is some fairly tight client-server integration; this is how I receive my progress of what's running in my windows service back into my windows app.</p>

<p>Now, all is great, the WCF gods are relatively happy with me right now apart from one nasty exception which I receive every time I shutdown the app prematurely (which is a perfectly valid scenario). Whilst a transfer is in progress, and callbacks are firing pretty heavily, I receive this error:</p>

<pre><code>System.ServiceModel.ProtocolException:
  The channel received an unexpected input message with Action 
  'http://tempuri.org/ITransferServiceContract/TransferSpeedChangedCallback' 
  while closing. You should only close your channel when you are not expecting 
  any more input messages.
</code></pre>

<p>Now I understand that error, but unfortunately I cannot guarantee to close my channel after never receiving any more input messsages, as the user may shutdown the app at any time therefore the work will still be continuing in the background of the windows service (kind of like how a virus scanner operates).  The user should be able to start and close the win management tool app as much as they like with no interference.</p>

<p>Now the error, I receive immediately after performing my <code>Unsubscribe()</code> call which is the second last call before terminating the app and what I believe is the preferred way to disconnect a WCF client. All the unsubscribe does before closing the connection is simply removes the client id from an array which was stored locally on the win service wcf service (as this is an instance SHARED by both the win service and windows app as the win service can perform work at scheduled events by itself) and after the client id array removal I perform, what I hope (feel) should be a clean disconnection.</p>

<p>The result of this, besides receiving an exception, is my app hangs, the UI is in total lock up, progress bars and everything mid way, with all signs pointing to having a race condition or WCF deadlock [sigh], but I am pretty thread-savvy now and I think this is a relatively isolated situation and reading the exception as-is, I don't think it's a 'thread' issue per-se, as it states more an issue of early disconnection which then spirals all my threads into mayhem, perhaps causing the lock up.</p>

<p>My <code>Unsubscribe()</code> approach on the <strong>client</strong> looks like this:</p>

<pre><code>    public void Unsubscribe()
    {
        try
        {
            // Close existing connections
            if (channel != null &amp;&amp;
                channel.State == CommunicationState.Opened)
            {
                proxy.Unsubscribe();
            }
        }
        catch (Exception)
        {
            // This is where we receive the 'System.ServiceModel.ProtocolException'.
        }
        finally
        {
            Dispose();
        }
    }
</code></pre>

<p>And my <code>Dispose()</code> method, which should perform the clean disconnect:</p>

<pre><code>    public void Dispose()
    {
        // Dispose object
        if (channel != null)
        {
            try
            {
                // Close existing connections
                Close();
                // Attempt dispose object
                ((IDisposable)channel).Dispose();
            }
            catch (CommunicationException)
            {
                channel.Abort();
            }
            catch (TimeoutException)
            {
                channel.Abort();
            }
            catch (Exception)
            {
                channel.Abort();
                throw;
            }
        }
    }
</code></pre>

<p>And the WCF service <code>Subscription()</code> counterpart and class attributes (for reference) on the windows service <strong>server</strong> (nothing tricky here and my exception occurs client side):</p>

<pre><code>    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, 
    ConcurrencyMode = ConcurrencyMode.Multiple)] 
    public class TransferService : LoggableBase, ITransferServiceContract
    {
        public void Unsubscribe()
        {
            if (clients.ContainsKey(clientName))
            {
                lock (syncObj)
                {
                    clients.Remove(clientName);
                }
            }

#if DEBUG
            Console.WriteLine(" + {0} disconnected.", clientName);
#endif
        }
        ...
    }
</code></pre>

<p>Interface of:</p>

<pre><code>[ServiceContract(
    CallbackContract = typeof(ITransferServiceCallbackContract), 
    SessionMode = SessionMode.Required)]
public interface ITransferServiceContract
{
    [OperationContract(IsInitiating = true)]
    bool Subscribe();

    [OperationContract(IsOneWay = true)]
    void Unsubscribe();
    ...
}
</code></pre>

<p>Interface of callback contract, it doesn't do anything very exciting, just calls events via delegates etc. The reason I included this is to show you my attributes.  I did alleviate one set of deadlocks already by including <code>UseSynchronizationContext = false</code>:</p>

<pre><code>[CallbackBehavior(UseSynchronizationContext = false, 
ConcurrencyMode = ConcurrencyMode.Multiple)]
public class TransferServiceCallback : ITransferServiceCallbackContract
{ ... }
</code></pre>

<p>Really hope somebody can help me! Thanks a lot =:)</p>

                    <div class="attribution">
                        This question originated from <a href="http://stackoverflow.com/questions/3740804" target="_blank">stackoverflow</a>
                    </div>
                </div>
                <div class="clear_l"></div>
            </div>
        </div>
        <div class="as2">
			<script type="text/javascript"><!--
			google_ad_client = "ca-pub-7610814771568026";
			/* codeinspot728 */
			google_ad_slot = "4091204029";
			google_ad_width = 728;
			google_ad_height = 90;
			//-->
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
        </div>
        <div class="ans_count">
            <h3>1 answers have been posted</h3>
        </div>
        <div class="answers">
            <ul>
                
                    <li class="a_c">
                        <div class="author">
                            <img src="http://www.gravatar.com/avatar/23fff93ede98c6cd922ef17b68b38a0c?d=identicon"/><br/>
                            <a href="http://stackoverflow.com/users/41211" class="a_link" target="_blank">GONeale</a>
                        </div>
                        <div class="a_t">
                                <p>OH my gosh, I found the issue.</p>

<p>That exception had nothing to do with the underyling app hang, that was just a precautionary exception which you can safely catch.</p>

<p>You would not believe it, I spent about 6 hours on and off on this bug, it turned out to be the <code>channel.Close()</code> locking up waiting for pending WCF requests to complete (which never would complete until the transfer has finished! which defeats the purpose!)</p>

<p>I just went brute-force breakpointing line after line, my issue was if I was too slow..... it would never hang, because somehow the channel would be available to close (even before the transfer had finished) so I had to breakpoint F5 and then quickly step to catch the hang, and that's the line it ended on.  I now simply apply a timeout value to the <code>Close()</code> operation and catch it with a <code>TimeoutException</code> and then hard abort the channel if it cannot shut down in a timely fashion! </p>

<p>See the fix code:</p>

<pre><code>private void Close()
{
    if (channel != null &amp;&amp;
        channel.State == CommunicationState.Opened)
    {
        // If cannot cleanly close down the app in 3 seconds,
        // channel is locked due to channel heavily in use
        // through callbacks or the like.
        // Throw TimeoutException
        channel.Close(new TimeSpan(0, 0, 0, 3));
    }
}

public void Dispose()
{
    // Dispose object
    if (channel != null)
    {
        try
        {
            // Close existing connections
            // *****************************
            // This is the close operation where we perform 
            //the channel close and timeout check and catch the exception.
            Close();

            // Attempt dispose object
            ((IDisposable)channel).Dispose();
        }
        catch (CommunicationException)
        {
            channel.Abort();
        }
        catch (TimeoutException)
        {
            channel.Abort();
        }
        catch (Exception)
        {
            channel.Abort();
            throw;
        }
    }
}
</code></pre>

<p>I am so happy to have this bug finally over and done with! My app is now shutting down cleanly after a 3 second timeout regardless of the current WCF service state, I hope I could have helped someone else who ever finds themselves suffering a similar issue.</p>

<p>Graham</p>

                        </div>
                        <div class="clear_l"></div>
                    </li>
                
            </ul>
            <div class="as3">
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-7610814771568026";
				/* codeinspot_link */
				google_ad_slot = "5655125578";
				google_ad_width = 728;
				google_ad_height = 15;
				//-->
				</script>
				<script type="text/javascript"
				src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-7610814771568026";
				/* codeinspot_link */
				google_ad_slot = "5655125578";
				google_ad_width = 728;
				google_ad_height = 15;
				//-->
				</script>
				<script type="text/javascript"
				src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
            </div>
        </div>
        <div id="m_answer">
            <h3>More Questions about WCF exception received on closing connection with callbacks in use</h3>
            <ul>
                
                    <li>
                        <a href="http://co.runcode.us/q/correct-way-to-close-database-connection-in-event-of-exception" title="Correct way to close database connection in event of exception.">Correct way to close database connection in event of exception.</a>
                    </li>
                
                    <li>
                        <a href="http://ja.runcode.us/q/java-sql-exception-closedconnection" title="java.sql.Exception ClosedConnection">java.sql.Exception ClosedConnection</a>
                    </li>
                
                    <li>
                        <a href="http://ho.runcode.us/q/how-to-close-db-connections-in-except-clause" title="how to close db connections in except clause">how to close db connections in except clause</a>
                    </li>
                
                    <li>
                        <a href="http://wh.runcode.us/q/why-exception-throws-while-closing-the-connection" title="Why exception throws while closing the connection?">Why exception throws while closing the connection?</a>
                    </li>
                
                    <li>
                        <a href="http://wi.runcode.us/q/winsock-how-to-stop-sending-receiving-without-closing-the-connection" title="Winsock: How to stop sending/receiving without closing the connection">Winsock: How to stop sending/receiving without closing the connection</a>
                    </li>
                
                    <li>
                        <a href="http://cl.runcode.us/q/closing-wcf-connection" title="Closing WCF connection">Closing WCF connection</a>
                    </li>
                
                    <li>
                        <a href="http://wc.runcode.us/q/wcf-connection-closed-notification" title="wcf connection closed notification">wcf connection closed notification</a>
                    </li>
                
                    <li>
                        <a href="http://se.runcode.us/q/setting-receivetimeout-for-callbacks-in-wcf" title="Setting receiveTimeout for callbacks in WCF?">Setting receiveTimeout for callbacks in WCF?</a>
                    </li>
                
                    <li>
                        <a href="http://ti.runcode.us/q/time-out-exception-on-wcf-callback" title="Time Out Exception On WCF Callback">Time Out Exception On WCF Callback</a>
                    </li>
                
                    <li>
                        <a href="http://wc.runcode.us/q/wcf-namedpipe-callback-timeout-exception" title="WCF namedpipe callback timeout exception">WCF namedpipe callback timeout exception</a>
                    </li>
                
                    <li>
                        <a href="http://pr.runcode.us/q/prevent-exceptions-from-wcf-callbacks" title="Prevent Exceptions From WCF Callbacks">Prevent Exceptions From WCF Callbacks</a>
                    </li>
                
                    <li>
                        <a href="http://to.runcode.us/q/tomcat-jndi-connection-pool-docs-random-connection-closed-exceptions" title="Tomcat JNDI Connection Pool docs - Random Connection Closed Exceptions">Tomcat JNDI Connection Pool docs - Random Connection Closed Exceptions</a>
                    </li>
                
                    <li>
                        <a href="http://do.runcode.us/q/does-end-using-close-an-open-sql-connection" title="Does End Using close an open SQL Connection">Does End Using close an open SQL Connection</a>
                    </li>
                
                    <li>
                        <a href="http://www.runcode.us/q/c-will-a-using-block-close-a-database-connection" title="C#: will a using block close a database connection?">C#: will a using block close a database connection?</a>
                    </li>
                
                    <li>
                        <a href="http://to.runcode.us/q/to-close-connection-to-database-after-i-use-or-not" title="to close connection to database after i use or not ?">to close connection to database after i use or not ?</a>
                    </li>
                
                    <li>
                        <a href="http://wc.runcode.us/q/wcf-client-getting-a-timeoutexception-and-i-am-closing-my-connections" title="WCF client getting a TimeoutException (and I AM closing my connections)">WCF client getting a TimeoutException (and I AM closing my connections)</a>
                    </li>
                
                    <li>
                        <a href="http://ca.runcode.us/q/catching-ftp-receive-connection-exceptions-in-biztalk" title="Catching FTP Receive Connection Exceptions in BizTalk">Catching FTP Receive Connection Exceptions in BizTalk</a>
                    </li>
                
                    <li>
                        <a href="http://do.runcode.us/q/does-closing-a-wcf-callback-channel-close-the-session-channel-too" title="Does closing a WCF callback channel close the session channel, too?">Does closing a WCF callback channel close the session channel, too?</a>
                    </li>
                
                    <li>
                        <a href="http://js.runcode.us/q/jsonp-not-receiving-any-callback" title="JSONP not receiving any callback?">JSONP not receiving any callback?</a>
                    </li>
                
                    <li>
                        <a href="http://ns.runcode.us/q/nsnotification-not-receiving-callback-everytime" title="NSNotification not receiving callback everytime">NSNotification not receiving callback everytime</a>
                    </li>
                
            </ul>
        </div>
    </div>
    
<div class="clear"></div>
<div id="footer">
    <div>
        The questions and answers are licensed under the cc-wiki license.<br/>
        Logo, design and layout © 2010 <a href="http://www.runcode.us" title="RunCode provides questions and answers about technology">RunCode.us</a>
        <a href="http://www.codeinspot.com" title="Technology Questions and Answers">CodeInSpot</a>
        <a href="http://www.huganswer.com" title="Find Questions and Answers from real people">HugAnswer</a>
    </div>
</div>
</div>
</body>
</html>
